# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v2
name: uds-portal
description: A Helm chart for Kubernetes
type: application
# x-release-please-start-version
version: 0.4.0
# x-release-please-end
