# Copyright 2025-2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

replicaCount: 1
image:
  repository: ghcr.io/defenseunicorns/uds-portal
  tag: "0.0.0-dev"
  pullPolicy: IfNotPresent
sso:
  enabled: true
package:
  gateway: tenant
  host: portal
  domain: "uds.dev"
  adminDomain: ""

# Default requests and limits when running only uds-core (increase for production)
resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "750m"

# add user and group for static chainguard image
podSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532
containerSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532

classificationBanner:
  enabled: false
  addFooter: false
  text: ""

adminApps:
  enabled: true

extraConfigmapMounts: []
