# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

[tools]
hk = "1.46.0"
"aqua:defenseunicorns/uds-cli" = "0.32.0"
"aqua:google/addlicense" = "1.2.0"
"aqua:k3d-io/k3d" = "5.9.0"
go = "1.26.3"
golangci-lint = "2.12.2"
pnpm = "11.5.1"
node = "24.14.1"
"npm:prettier" = "3.8.3"
pkl = "0.31.1"
uv = "0.11.18"                             # required to install yamllint
yamllint = "1.38.0"

[env]
# Disables version download tracking introduced in 2025.12.6, see:
# https://mise.jdx.dev/configuration/settings.html#use_versions_host_track
MISE_USE_VERSIONS_HOST_TRACK = "0"
