# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uds-portal-cluster-role
rules:
  - apiGroups: ["uds.dev"]
    resources: ["packages"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
