# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: uds-portal-zarf-secrets-role
  namespace: zarf
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
