# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uds-portal-zarf-secrets-role-binding
  namespace: zarf
subjects:
  - kind: ServiceAccount
    name: uds-portal-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: uds-portal-zarf-secrets-role
  apiGroup: rbac.authorization.k8s.io
