# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

includes:
  - setup: https://raw.githubusercontent.com/defenseunicorns/uds-common/v1.24.5/tasks/setup.yaml
  - build: ./build.yaml
  - core-utils: https://raw.githubusercontent.com/defenseunicorns/uds-core/refs/tags/v1.2.0/tasks/utils.yaml

tasks:
  - name: deploy-app-portal-cluster
    description: deploy cluster specifically for testing UDS Portal
    actions:
      - task: setup:k3d-test-cluster
      - task: deploy-load

  - name: local-auth
    description: "run end-to-end tests (assumes api server is running on port 8080)"
    actions:
      - task: build:ui
      - cmd: pnpm run test:install # install playwright
        dir: ui
      - task: build:api
      - task: setup:k3d-test-cluster
      - task: deploy-load
      - cmd: pnpm run test:local-auth
        dir: ui

  - name: deploy-load
    description: "deploy some Zarf packages to test against"
    actions:
      - cmd: uds zarf dev deploy
        dir: ui/tests/packages/podinfo

  - name: deploy-podinfo
    description: "deploy podinfo to the cluster"
    actions:
      - cmd: uds zarf package create --confirm
        dir: ui/tests/packages/podinfo
      - cmd: uds zarf package deploy zarf-package-podinfo-test-$UDS_ARCH-0.0.1.tar.zst --confirm
        dir: ui/tests/packages/podinfo
      - description: Validate podinfo pod
        wait:
          cluster:
            kind: Pod
            name: app.kubernetes.io/name=podinfo
            condition: Ready
            namespace: podinfo
        maxTotalSeconds: 240

  - name: e2e
    description: "run end-to-end tests (assumes api server is running on port 8080)"
    actions:
      - task: build:ui
      - cmd: pnpm run test:install # install playwright
        dir: ui
      - task: build:api
      - task: deploy-app-portal-cluster
      - cmd: pnpm run test:e2e
        dir: ui

  - name: go-unit
    description: "run api server unit tests"
    actions:
      - cmd: go test -failfast -v -timeout 30m ./src/pkg/...

  - name: ui-unit
    description: "run frontend unit tests"
    actions:
      - cmd: pnpm install --frozen-lockfile && pnpm run test:unit
        dir: ui

  - name: unit
    description: "run all unit tests (backend and frontend)"
    actions:
      - task: build:ui
        description: "build ui since embedded in main.go"
      - task: go-unit
      - task: ui-unit
