# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  tag: nightly-unstable
  pullPolicy: Always
package:
  gateway: tenant
  host: runtime-canary
  domain: "###ZARF_VAR_DOMAIN###"
