# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: PR Title and Commit Lint

permissions:
  pull-requests: read
  contents: read

on:
  pull_request:
    branches: [main]
    # `milestoned` is a workaround for release-please not triggering PR workflows
    # (PRs should be added to a milestone to trigger). `reopened` covers PRs
    # release-please reopens after merge.
    types: [milestoned, opened, reopened, edited, synchronize]

concurrency:
  group: commitlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-title-lint:
    name: PR Title Lint
    uses: defenseunicorns/uds-common/.github/workflows/callable-commitlint.yaml@ef8767c2d84fc4d23c37f3b7dac3c6292ee76c11 # v1.25.0
