---
# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release UDS Portal

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  tag-new-version:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      release_created: ${{ steps.tag.outputs.release_created }}
      tag_name: ${{ steps.tag.outputs.tag_name }}
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Create release tag
        id: tag
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          target-branch: ${{ github.ref_name }}

  release:
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true' }}
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ needs.tag-new-version.outputs.tag_name }}

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          # renovate: datasource=github-releases depName=jdx/mise versioning=semver
          version: 2026.7.0
          install: true
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to GHCR
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: uds run release:publish --set VERSION=${{ needs.tag-new-version.outputs.version }}
