# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release UDS App Portal

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  tag-new-version:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.tag.outputs.release_created }}
    steps:
      - name: Create release tag
        id: tag
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        with:
          target-branch: ${{ github.ref_name }}
