# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release UDS App Portal

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  tag-new-version:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      release_created: ${{ steps.tag.outputs.release_created }}
    steps:
      - name: Create release tag
        id: tag
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          target-branch: ${{ github.ref_name }}
