# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Test

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.png"
      - "**.jpg"
      - "**.svg"
      - "**.gif"
      - "CODEOWNERS"
      - "LICENSE*"

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-paths:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      app: ${{ steps.filter.outputs.app }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check paths
        id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            app:
              - 'src/**'
              - 'ui/**'
              - 'main.go'
              - 'go.mod'
              - 'go.sum'
              - 'Dockerfile'
              - 'chart/**'
              - 'zarf.yaml'
              - 'mise.toml'

  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          # renovate: datasource=github-releases depName=jdx/mise versioning=semver
          version: 2026.6.14
          install: true
          cache: true

      - name: Run unit tests
        run: uds run test:unit

  e2e:
    needs: [check-paths, unit]
    if: needs.unit.result == 'success' && (needs.check-paths.outputs.app == 'true' || !startsWith(github.head_ref, 'renovate/'))
    permissions:
      contents: read
      id-token: write
    runs-on: uds-ubuntu-big-boy-4-core
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          # renovate: datasource=github-releases depName=jdx/mise versioning=semver
          version: 2026.6.14
          install: true
          cache: true

      - name: Login to Chainguard
        uses: chainguard-dev/setup-chainctl@2cddd35a2f120d9973e58094dc6878c93cf58c28 # v0.5.1
        with:
          identity: ${{ secrets.CHAINGUARD_IDENTITY }}

      - name: Setup e2e environment
        run: uds run test:e2e-setup

      - name: Run e2e tests
        run: uds run test:e2e
