# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: lint-check
description: "Check project for linting errors"

inputs:
  yamllint-version:
    description: 'yamllint version to use'
    required: true
    # renovate: datasource=pypi depName=yamllint
    default: '1.37.1'
  addlicense-version:
    description: 'addlicense version to use'
    required: true
    # renovate: datasource=github-releases depName=google/addlicense
    default: 'v1.1.1'

runs:
  using: composite
  steps:
    - name: Environment setup
      uses: ./.github/actions/setup-tools
      with:
        installUv: 'true'

    - name: Install yamllint
      run: uv tool install yamllint==${{ inputs.yamllint-version }}
      shell: bash

    - name: Install addlicense
      run: go install github.com/google/addlicense@${{ inputs.addlicense-version }}
      shell: bash

    - name: Run linting checks
      run: uds run lint-check --no-progress
      shell: bash
